package token

var keywords = map[string]Kind{
	"package":     KWPackage,
	"import":      KWImport,
	"func":        KWFunc,
	"var":         KWVar,
	"int":         KWInt,
	"int8":        KWInt8,
	"int32":       KWInt32,
	"int64":       KWInt64,
	"uint":        KWUint,
	"uint8":       KWUint8,
	"uint32":      KWUint32,
	"uint64":      KWUint64,
	"float":       KWFloat,
	"float32":     KWFloat32,
	"float64":     KWFloat64,
	"const":       KWConst,
	"string":      KWString,
	"type":        KWType,
	"struct":      KWStruct,
	"interface":   KWInterface,
	"if":          KWIf,
	"else":        KWElse,
	"for":         KWFor,
	"break":       KWBreak,
	"continue":    KWContinue,
	"switch":      KWSwitch,
	"case":        KWCase,
	"default":     KWDefault,
	"fallthrough": KWFallThrough,
	"return":      KWReturn,
	"bool":        KWBool,
	"true":        BoolLit,
	"false":       BoolLit,
}

var builtinTypes = map[Kind]bool{
	KWInt:       true,
	KWInt8:      true,
	KWInt32:     true,
	KWInt64:     true,
	KWUint:      true,
	KWUint8:     true,
	KWUint32:    true,
	KWUint64:    true,
	KWFloat:     true,
	KWFloat32:   true,
	KWFloat64:   true,
	KWConst:     true,
	KWString:    true,
	KWBool:      true,
	KWType:      true,
	KWStruct:    true,
	KWInterface: true,
}
